# Generated by Django 3.2.5 on 2023-07-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='last_send_file_date',
            field=models.DateTimeField(blank=True, help_text='Дата последней отправки данных анкеты в Битрикс', null=True, verbose_name='Дата последней отправки'),
        ),
    ]
