# Generated by Django 3.2.5 on 2023-09-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_questionnaire_last_send_file_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='last_send_keywords_date',
            field=models.DateTimeField(blank=True, help_text='Дата последней отправки ключевых слов пациента в Битрикс', null=True, verbose_name='Дата последней отправки ключевых слов'),
        ),
    ]
